# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='assets')),
                ('post_title', models.CharField(max_length=100)),
                ('post_content', models.TextField(blank=True)),
                ('post_date', models.DateTimeField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
